services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: csv_pickle_app
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./backend:/app/backend
      - ./config.py:/app/config.py
      - ./.env:/app/.env
      - ./storage:/app/storage
      - app_sqlite:/app
    environment:
      - APP_NAME=CSV/JSON to Pickle Converter API
      - DEBUG=True
      - DATABASE_URL=sqlite:///./app.db
      - STORAGE_DIR=./storage
    restart: always

volumes:
  app_sqlite:
